language: python
install:
  - pip install -U pip
  - pip install pyyaml rfc3987 jsonschema yamllint requests
jobs:
  include:
    - stage: check_poc
      script: 
        - git remote set-branches --add origin master
        - git fetch
        - python tests/tests.py