language: go
install:
  - sudo apt update
  - sudo apt install -y python3-pip python3-setuptools
  - pip3 install pyyaml rfc3987 jsonschema yamllint requests
jobs:
  include:
    - stage: check_poc
      script: 
        - git remote set-branches --add origin master
        - git fetch
        - python3 tests/tests.py
        - cd tests/cellint
        - export GO111MODULE=on
        - go mod download
        - go run cmd/cellint.go $(find ../../pocs -name "*.yml")