name: poc-yaml-swagger-ui-unauth
rules:
  - method: GET
    path: /
    follow_redirects: true
    expression: |
      response.status == 200 && response.body.bcontains(b"<div id=\"swagger-ui\">") && response.body.bcontains(b"./swagger-ui.css")
detail:
  author: Aquilao(https://github.com/Aquilao)
  links:
    - https://blog.csdn.net/u010192145/article/details/89514376
