name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare
      run: wget https://github.com/chaitin/xray/releases/download/0.16.5/xray_linux_amd64.zip && pip3 install yamllint && unzip xray_linux_amd64.zip
    - name: check poc
      run: ./xray_linux_amd64 poclint --poc "./pocs/*" --rules filename,filepath,yamlschema,yamllint,cellint
